/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillTable: typeof import("./src/components/billTable.vue")["default"]
    DataChart: typeof import("./src/components/DataChart.vue")["default"]
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    FeedbackForm: typeof import("./src/components/FeedbackForm.vue")["default"]
    GeneralPageOutline: typeof import(
    HeaderAvatar: typeof import('./src/components/HeaderAvatar.vue')['default']
    LoadingSpinner: typeof import(
    LoginCard: typeof import("./src/components/LoginCard.vue")["default"]
    NewConnectionCard: typeof import(
    NewConnectionForm: typeof import('./src/components/NewConnectionForm.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PayNowForm: typeof import('./src/components/PayNowForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceTemplate: typeof import('./src/components/ServiceTemplate.vue')['default']
    ServiceView: typeof import("./src/components/ServiceView.vue")["default"]
    SummaryNumbersChart: typeof import('./src/components/SummaryNumbersChart.vue')['default']
    SupportForm: typeof import("./src/components/SupportForm.vue")["default"]
    Test: typeof import("./src/components/test.vue")["default"]
  }
}
