/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillTable: typeof import('./src/components/billTable.vue')['default']
    DataChart: typeof import('./src/components/DataChart.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    FeedbackForm: typeof import('./src/components/FeedbackForm.vue')['default']
    GeneralPageOutline: typeof import('./src/components/generalPageOutline.vue')['default']
    HeaderAvatar: typeof import('./src/components/headerAvatar.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    NewConnectionCard: typeof import('./src/components/NewConnectionCard.vue')['default']
    NewConnectionForm: typeof import('./src/components/NewConnectionForm.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader.vue')['default']
    PayNowForm: typeof import('./src/components/PayNowForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceTemplate: typeof import('./src/components/ServiceTemplate.vue')['default']
    ServiceView: typeof import('./src/components/ServiceView.vue')['default']
    SummaryNumbersChart: typeof import('./src/components/summaryNumbersChart.vue')['default']
    SupportForm: typeof import('./src/components/SupportForm.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
